// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: migration.sql

package db

import (
	"context"
)

const migrationMessage = `-- name: MigrationMessage :one
SELECT message
FROM initial_migration
         LIMIT 1
`

func (q *Queries) MigrationMessage(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, migrationMessage)
	var message string
	err := row.Scan(&message)
	return message, err
}
