// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (ScratchUser, error)
	GetSession(ctx context.Context, arg GetSessionParams) (ScratchSession, error)
	GetUserByEmail(ctx context.Context, email string) (ScratchUser, error)
}

var _ Querier = (*Queries)(nil)
