// Code generated by MockGen. DO NOT EDIT.
// Source: session.go

// Package session is a generated GoMock package.
package session

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIdentityGenerator is a mock of IdentityGenerator interface.
type MockIdentityGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityGeneratorMockRecorder
}

// MockIdentityGeneratorMockRecorder is the mock recorder for MockIdentityGenerator.
type MockIdentityGeneratorMockRecorder struct {
	mock *MockIdentityGenerator
}

// NewMockIdentityGenerator creates a new mock instance.
func NewMockIdentityGenerator(ctrl *gomock.Controller) *MockIdentityGenerator {
	mock := &MockIdentityGenerator{ctrl: ctrl}
	mock.recorder = &MockIdentityGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityGenerator) EXPECT() *MockIdentityGeneratorMockRecorder {
	return m.recorder
}

// GenerateTokens mocks base method.
func (m *MockIdentityGenerator) GenerateTokens(userID string) (UserSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTokens", userID)
	ret0, _ := ret[0].(UserSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTokens indicates an expected call of GenerateTokens.
func (mr *MockIdentityGeneratorMockRecorder) GenerateTokens(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTokens", reflect.TypeOf((*MockIdentityGenerator)(nil).GenerateTokens), userID)
}

// ValidateToken mocks base method.
func (m *MockIdentityGenerator) ValidateToken(t string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", t)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockIdentityGeneratorMockRecorder) ValidateToken(t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockIdentityGenerator)(nil).ValidateToken), t)
}
