openapi: 3.0.3
info:
  title: Scratch
  version: 0.0.1
paths:
  /login:
    post:
      summary: login services
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginUserRequest"
      responses:
        '200':
          description: "login services"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginUserResponse"
        '400':
          description: "problem to login"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '500':
          description: "internal server error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /register:
    post:
      summary: register services
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterUserRequest"
      responses:
        '201':
          description: "services created"
          content:
            application/json:
              schema:
               type: object
               properties:
                 id:
                   type: string
        '400':
          description: "services already exist"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '404':
          description: "services not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '500':
          description: "Internal server error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /user/{id}:
    get:
      summary: "get services by id"
      security:
        - BearerAuth: [ ]
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: "services id"
      responses:
        '200':
          description: "services with data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetUserResponse"
        '404':
          description: "services not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '500':
          description: "internal server error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    LoginUserRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    LoginUserResponse:
      type: object
      properties:
        refreshToken:
          type: string
        token:
          type: string
      required:
        - refreshToken
        - token
    RegisterUserRequest:
      type: object
      properties:
        email:
          type: string
        name:
          type: string
        password:
          type: string
      required:
        - email
        - name
        - password
    GetUserResponse:
      type: object
      properties:
        email:
          type: string
        name:
          type: string
      required:
        - email
        - name
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
      required:
        - error